day23/day23/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url=r'/webapp/')),
    url(r'^webapp/', include("webapp.urls", namespace='webapp', app_name='webapp')),
]

day23/webapp/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Author  : Coosh

import os, sys, datetime
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^staff/$', views.staff_index, name='staff'),
    url(r'^staff/attendance/$', views.attendance, name='attendance'),
    url(r'^staff/score/$', views.score, name='score'),
    url(r'^staff/manage_student/$', views.manage_student_list, name='manage_student_list'),
    url(r'^staff/manage_student/(\d+)/$', views.manage_student, name='manage_student'),
    url(r'^staff/manage_student/(?P<student_id>\d+)/attendance/(?P<course_id>\d+)/$', views.get_student_attendance_by_course, name='get_student_attendance_by_course'),
    url(r'^staff/consult/$', views.consult, name='consult'),
    url(r'^staff/consult/chat/$', views.consult_chat, name='consult_chat'),
    url(r'^staff/consult/staff_get_msg/$', views.staff_get_msg, name='staff_get_msg'),
    url(r'staff/consult/get_handling/$', views.get_handling, name='get_handling'),
    url(r'staff/consult/save_client_info/$', views.save_client_info, name='save_client_info'),
    url(r'staff/consult/close_a_consult/$', views.close_a_consult, name='close_a_consult'),
    url(r'^staff/follow_up/$', views.follow_up, name='follow_up'),
    url(r'^staff/follow_up/detail/(\d+)/$', views.follow_up_detail, name='follow_up_detail'),
    url(r'^staff/follow_up/detail/new/$', views.new_client, name='new_client'),
    url(r'^staff/follow_up/no_more/$', views.no_more_follow, name='no_more_follow'),
    url(r'^staff/experiencing/$', views.experiencing, name='experiencing'),
    url(r'^staff/exp_course/$', views.exp_course, name='exp_course'),
    url(r'^staff/load_courses/area/(\d+)/$', views.load_courses, name='load_courses'),
    url(r'^student/$', views.student_index, name='student'),
    url(r'^consult/$', views.consult_from_guest, name='consult_from_guest'),
    url(r'^consult/staff_get_msg/$', views.client_get_msg, name='client_get_msg'),
]

day23/webapp/models.py
from django.db import models
from django.db.models import functions
from django.contrib.auth.hashers import make_password, check_password
from django.utils.translation import ugettext_lazy as _


# 校区，一个学员或班级仅属于一个校区，但一个老师或顾问可能属于多个校区
class Area(models.Model):
    name = models.CharField(max_length=30, unique=True)
    address = models.TextField(null=True, blank=True)
    telephone = models.CharField(max_length=32, null=True, blank=True)

    def __str__(self):
        return self.name


# Staff员工角色表，讲师\课程顾问，将来可以添加
# 一个人可以有多个角色
class StaffRole(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name


# 员工状态代码表，在职、离职
class StaffStatus(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name


class TeacherManager(models.Manager):
    def get_queryset(self):
        role = StaffRole.objects.get(name='讲师')
        return super(TeacherManager, self).get_queryset().filter(roles=role, status__name='在职')


class AdvisorManager(models.Manager):
    def get_queryset(self):
        role = StaffRole.objects.get(name='课程顾问')
        return super(AdvisorManager, self).get_queryset().filter(roles=role)


# 员工表，包含老师和课程顾问
class StaffInfo(models.Model):
    objects = models.Manager()
    teachers = TeacherManager()
    advisors = AdvisorManager()
    sysname = models.CharField(max_length=30, unique=True, verbose_name='登录名')  # 系统名，用于登录
    cname = models.CharField(max_length=30, verbose_name='中文名')     # 中文名
    gender = models.CharField(max_length=3, choices=(('男', '男'), ('女', '女'), ), verbose_name='性别')
    phone = models.CharField(max_length=20, verbose_name='电话')
    password = models.CharField(_('password'), max_length=64)
    status = models.ForeignKey('StaffStatus', verbose_name='状态')
    # area = models.ManyToManyField('Area')   # 一个员工可以属于多个校区
    area = models.ForeignKey('Area', verbose_name='属区')   # 员工所属校区
    roles = models.ForeignKey('StaffRole', verbose_name='职位')     # 员工角色
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.cname

    def set_password(self, raw_password):
        """暂不使用加密"""
        self.password = make_password(raw_password)


# 课程班级表，
# 一个同学或者老师可以属于多个课程
class Course(models.Model):
    name = models.CharField(max_length=64, verbose_name='课程名称')
    volume = models.PositiveIntegerField()  # 第几期
    start_time = models.DateField(null=True, blank=True)
    area = models.ForeignKey("Area")
    monitor = models.ForeignKey('StudentInfo', null=True, blank=True)  # 班长
    teachers = models.ManyToManyField('StaffInfo')      # 多个老师
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    avg_score = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = (('name', 'volume', 'area'),)     # 课程名 + 期 + 校区 联合唯一

    def __str__(self):
        return self.name


# 学员状态代码表，未报名前,报名后,毕业老学员，将来可以添加
class StudentStatus(models.Model):
    name = models.CharField(max_length=30, unique=True)
    def __str__(self):
        return self.name


# 学员表
class StudentInfo(models.Model):
    area = models.ForeignKey(Area)
    name = models.CharField(max_length=64)
    password = models.CharField(max_length=256, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    gender = models.CharField(choices=(('男', '男'), ('女', '女'), ), max_length=3, null=True, blank=True)
    phone = models.CharField(max_length=20)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    # updated_by = models.ForeignKey('StaffInfo')
    status = models.ForeignKey('StudentStatus')     # 状态：未报名前,报名后,毕业老学员
    courses = models.ManyToManyField('Course', blank=True)      # 多门课程
    client = models.ForeignKey('ClientInfo', null=True, blank=True, related_name="student")        # 客户编号

    class Meta:
        unique_together = (('name', 'gender', 'phone'),)

    def __str__(self):
        return self.name


# 成绩表
class CourseScore(models.Model):
    student = models.ForeignKey("StudentInfo")
    course = models.ForeignKey('Course')
    score = models.PositiveIntegerField()
    # test_at = models.DateTimeField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(StaffInfo)


# 出勤表
class Attendance(models.Model):
    course = models.ForeignKey('Course')
    student = models.ForeignKey('StudentInfo')
    attend_time = models.DateTimeField(auto_now_add=True)


# 客户信息表
class ClientInfo(models.Model):
    name = models.CharField(max_length=64)
    phone = models.CharField(max_length=64, null=True, blank=True)
    qq = models.PositiveIntegerField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    remark = models.TextField(null=True, blank=True)
    token = models.OneToOneField('SessionTokens', blank=True, null=True)
    source = models.CharField(max_length=20, choices=(
        ('consult', '客户咨询'),
        ('manual', '手工添加')
    ), default='consult')
    create_at = models.DateTimeField(auto_now_add=True)
    dont_follow = models.BooleanField(default=False)
    from_staff = models.ForeignKey('StaffInfo', null=True, blank=True)


# 客户咨询记录
class ClientConsult(models.Model):
    session = models.ForeignKey('SessionTokens')     # 对应哪个会话
    msg = models.TextField()    # 消息内容
    from_client = models.BooleanField()     # 是否客户的消息，否代表客服的回答
    create_at = models.DateTimeField(auto_now_add=True)


# 咨询会话令牌，访客第一次访问时，在此表生成一个令牌，每次POST提交咨询内容时必须带有有效令牌
class SessionTokens(models.Model):
    token = models.CharField(max_length=64, unique=True)
    client_ip = models.GenericIPAddressField()
    source = models.CharField(max_length=20, default="web")    # 咨询来源
    staff = models.ForeignKey('StaffInfo', blank=True, null=True)
    active = models.BooleanField(default=True)
    client = models.ForeignKey("ClientInfo", null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)


# 后续跟进记录
class ClientFollowUp(models.Model):
    client = models.ForeignKey("ClientInfo")
    staff = models.ForeignKey("StaffInfo")
    follow_time = models.DateTimeField(auto_now_add=True)
    result = models.TextField()

day23/webapp/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Author  : Coosh

from django import forms
from django.contrib.admin import widgets
from .models import *


class LoginForm(forms.Form):
    username = forms.CharField(max_length=60, required=True)
    password = forms.CharField(widget=forms.PasswordInput, required=True)


# class ScoreForm(forms.ModelForm):
#     class Meta:
#         model = CourseScore
#         fields = ("course", "score", "test_at")


class FollowUp(forms.ModelForm):
    class Meta:
        model = ClientFollowUp
        fields = ("result", )
        labels = {"result": "跟进结果", }


class ClientInfoForm(forms.ModelForm):
    class Meta:
        model = ClientInfo
        fields = ("name", "phone", "qq", "email", "remark",)
        labels = {"name": "称谓",
                  "phone": "电话",
                  "qq": "QQ",
                  "remark": "备注",
                  }
        widgets = {
            "phone": forms.TextInput,
            "qq": forms.TextInput,
        }

    def clean(self):
        cleaned_data = super(ClientInfoForm, self).clean()
        if not (cleaned_data.get("phone") or cleaned_data.get("qq") or  cleaned_data.get("email")):
            raise forms.ValidationError("电话、Email、QQ，至少需提供一个")

day23/webapp/templates/app/attendance-course.html
{% load staticfiles %}
<div>
    <h1>{{ course.name }} 第{{ course.volume }}期</h1>
{#    <p>开课时间 {{ course.start_time|date:'Y-m-d' }}</p>#}
    <p>当前日期 {{ current_date|date:'Y-m-d' }}</p>
    <p>主讲：
    {% for teacher in course.teachers.all %}
    {{ teacher.cname }}&nbsp;
    {% endfor %}
    </p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>到场</th>
                <th>姓名</th>
                <th>性别</th>
                <th>状态</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <td>
                    {% if student.id in attended_students %}
                    <span>√</span>{#&nbsp;&nbsp;<a href="javascript:void(0);" onclick="attend(this, {{ student.id }}, 'cancel')" >取消</a>#}
                    {% else %}
                     <button onclick="attend(this,{{ student.id }}, 'attend')">到</button>
                    {% endif %}
                    <img src="{% static "webapp/img/loading.gif" %}" class="hide">
                </td>
                <td>{{ student.name }}</td>
                <td>{{ student.gender }}</td>
                <td>{{ student.status.name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <script>
        // 签到函数
        function attend(ele, sid, action) {
{#            $(ele).parent().parent().find('td:first-child').text('√');#}
            var data = {};
            data.student_id = sid;
            data.action = action;
            $(ele).addClass('hide').siblings('img').removeClass('hide');
            $.post({
                url: "/webapp/staff/attendance/?course_id={{ course.id }}",
                data: data,
                dataType: "json",
                success: function (response) {
                    if(response.status=='ok'){
                        $(ele).parent().parent().find('td:first-child').text('√');
                    }
                },
                error: function () {

                }
            })
        }
    </script>
</div>

day23/webapp/templates/app/attendance-courses-list.html
<h1 class="page-header">课程信息</h1>
<div>
    {% if courses %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>课名</th>
                    <th>期数</th>
                    <th>开课日期</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for c in courses %}
                <tr>
                    <td>{{ c.name }}</td>
                    <td>{{ c.volume }}</td>
                    <td>{{ c.start_time|date:'Y-m-d' }}</td>
                    <td><a href="javascript:void(0);" data-url="/webapp/staff/attendance/?course_id={{ c.id }}" onclick="attendance(this)">开始考勤</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <script>
            function attendance(ele) {
                var url = $(ele).attr('data-url');
                $.get({
                    url: url,
                    dataType: "html",
                    success: function(response) {
                        $('div.main').html(response);
                    }
                })
            }
        </script>
    {% else %}
        好像没有您主持的课程哟
    {% endif %}
</div>

day23/webapp/templates/app/base-staff.html
{% extends "base.html" %}
{% block title %}员工首页{% endblock %}
{% block content %}
<h2 class="page-header">{{ user.name }} {{ user.cname }} 欢迎你</h2>
{% endblock %}

day23/webapp/templates/app/consult-staff-page.html
{# 在管理页面的内嵌页 #}
<div>
    <div>
        待处理的咨询：<span class="untreated-num"></span>个
        <button onclick="get_a_job()">处理</button>
    </div>
    <div>
        我处理中的咨询：
        <div class="handling-consult">

        </div>
    </div>
    <div>
        我处理完的咨询
        <div class="handled-consult">

        </div>
    </div>
    <script>
        function check_consult_num() {
            // 获取有多少个待处理的咨询
            //console.log("yes");
            $.get({
                url: "/webapp/staff/consult/",
                data: {"action": "check_consult_num"},
                dataType: "json",
                timeout: 3000,
                success:function (response) {
                    //console.log(response);
                    var num = response.count;
                    $("span.untreated-num").text(num);
                },
                error: function (r,s,t) {
                    console.log(r);
                    console.log(s);
                    console.log(t);
                }
            });
        }

        function get_a_job() {
            // 向服务器领取一个待处理的咨询的token
            $.get({
                url: "consult/",
                data:{"action": "get_a_job"},
                dataType:"json",
                success:function (response) {
                    var token = response.token;
                    var source = response['source'];
                    open_a_consult(token);
                }
            });
        }
        function open_a_consult(token) {
            // 打开一个咨询页面
            //var current_url = window.location.href;
            //console.log(current_url);
            // window.open("consult/?action=open_a_consult&token=" + token);
            window.open("consult/chat/?token=" + token);
        }

        function get_handling() {
            $.get({
                url:"/webapp/staff/consult/get_handling/",
                dataType: "json",
                success: function (response) {
                    console.log(response);
                    var f = function (l,ele,t) {
                        if(l.length>0){
                        // 有处理中的咨询，生成ul li元素
                            var ul = document.createElement('ul');
                            for(var key in l){
                                var li = document.createElement('li');
                                var a = document.createElement('a');
                                a.href = "consult/chat/?token=" + l[key].token;
                                a.target = "_blank";
                                a.innerText = l[key].create_at + " " + (l[key].clientinfo__name||"");
                                li.appendChild(a);
                                ul.appendChild(li);
                            }
                            $(ele).html(ul.outerHTML);
                        }else{
                            $(ele).text(t);
                        }
                    };
                    f(response['handling_list'],"div.handling-consult","没有处理中的咨询");
                    f(response['finished_list'],"div.handled-consult","没有处理完的咨询");
{#                    if(response.length>0){#}
{#                        // 有处理中的咨询，生成ul li元素#}
{#                        var ul = document.createElement('ul');#}
{#                        for(var key in response){#}
{#                            var li = document.createElement('li');#}
{#                            var a = document.createElement('a');#}
{#                            a.href = "consult/chat/?token=" + response[key].token;#}
{#                            a.target = "_blank";#}
{#                            a.innerText = response[key].create_at;#}
{#                            li.appendChild(a);#}
{#                            ul.appendChild(li);#}
{#                        }#}
{#                        $("div.handling-consult").html(ul.outerHTML);#}
{#                    }else{#}
{#                        $("div.handling-consult").text("没有处理中的咨询");#}
{#                    }#}
                }
            });
        }

        // 循环读取目前有多少待处理咨询，间隔为1秒
        var untreated_int = setInterval("check_consult_num()", 1000);
        get_handling();

    </script>
</div>

day23/webapp/templates/app/followup-detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>客户跟进情况</title>
    <link href="{% static "webapp/css/bootstrap.min.css" %}" rel="stylesheet">
    <style>
        body{
            padding: 10px 20px;
        }
        caption{
            font-size: 3em;
        }
        table.new_form th{
            vertical-align: top;
            padding-right: 10px;
        }
        .fl{
            float: left;
        }
        .clearfix:after{
            content: ".";
            clear: both;
            display: block;
            visibility: hidden;
            height: 0;
        }
        div.client_info, div.actions, div.history{
            margin-bottom: 30px;
        }
        div.client_info th{
            background-color: #9acfea;
        }
        div.client_info th, div.client_info td{
            padding: 10px 20px;
        }
        .add_record, .no_follow_anymore, .experiencing{
            width: 350px;
        }
        .actions textarea{
            width: 250px;
            height: 200px;
            padding: 5px;
        }
    </style>
</head>
<body>
    <div>
        <div>
            <div class="client_info">
                <table border="1">
                    <caption>客户资料{% if ci.dont_follow %}
                    （不再跟进）
                    {% endif %}</caption>
                    <tr>
                        <th>称谓</th><td>{{ ci.name }}</td>
                        <th>电话</th><td>{{ ci.phone }}</td>
                        <th>QQ</th><td>{{ ci.qq }}</td>
                    </tr>
                    <tr>
                        <th>邮箱</th><td>{{ ci.email }}</td>
                        <th>来源</th><td>{{ ci.get_source_display }}</td>
                        <th>录入员</th><td>{{ ci.from_staff.cname }}</td>
                    </tr>
                    <tr>
                        <th>备注</th><td colspan="5">{{ ci.remark|linebreaks }}</td>
                    </tr>
                </table>
            </div>
            <h1>操作</h1>
            <div class="actions clearfix">
                <div class="add_record fl">
                    <form method="post">
                        {% csrf_token %}
                        <table class="new_form">
                            {{ new_form.as_table }}
                        </table>
                        <input type="submit" value="添加">
                    </form>
                </div>
                <div class="experiencing fl">
                    安排试听
                    <br>
                    <label>
                        校区
                        <select id="area" onchange="load_courses()">
                            <option></option>
                            {% for area in areas %}
                            <option value="{{ area.id }}">{{ area.name }}</option>
                            {% endfor %}
                        </select>
                    </label>
                    <br>
                    <label>
                        课程
                        <select id="course" disabled="disabled">
                            <option></option>
                        </select>
                    </label>
                    <br>
                    <button onclick="experiencing()">安排试听</button>
                </div>
                <div class="no_follow_anymore fl">
                    <label>
                        <textarea placeholder="请填写不再跟进的原因"></textarea>
                    </label>
                    <br>
                    <button onclick="no_follow_anymore()">不再跟进</button>
                </div>
            </div>
            <div class="history">
                {% if history %}
                    <table class="table table-bordered table-hover">
                    <caption>历史记录</caption>
                        <thead>
                            <tr>
                                <th>时间</th>
                                <th>记录</th>
                                <th>跟进人员</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for record in history %}
                            <tr>
                                <td>
                                    {{ record.follow_time|date:'Y-m-d H:i:s' }}
                                </td>
                                <td>
                                    {{ record.result|linebreaks }}
                                </td>
                                <td>
                                    {{ record.staff.cname }}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    暂无跟进记录
                {% endif %}
            </div>
        </div>
    </div>
    <script src="{% static "webapp/js/jquery-1.12.4.min.js" %}"></script>
    <script src="{% static "webapp/js/jquery.cookie.js" %}"></script>
    <script>
        var client_id="{{ ci.id }}";
        var csrftoken = $.cookie('csrftoken');  // 获取cookie中csrftoken值
        function csrfSafeMethod(method) {
            // 这个函数用于判断请求的方法，如果匹配的话，则返回true；主要目的是这些方法不需要修改头信息
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        // $.ajaxSetup是jQuery的特有方法，用于在ajax发起之前和之后的动作
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        function no_follow_anymore() {
            // 操作人员确认
            if(!confirm("确定不再跟进吗？"))
                return false;

            $.post({
                url:'/webapp/staff/follow_up/no_more/',
                data:{"cid": client_id, "reason": $("div.no_follow_anymore textarea").val()},
                dataType:"json",
                success:function (response) {
                    if(response.status=='ok')
                        alert("操作成功！");
                    window.location.reload();
                }
            });
        }

        // ajax获取所选校区的所有课程
        function load_courses() {
            //console.log($("#area").val());
            $.get({
                url:"/webapp/staff/load_courses/area/"+$("#area").val()+"/",
                dataType:"json",
                success:function (response) {
                    $("#course option[value]").remove();
                    $("#course").attr("disabled", true);
                    if(response.length>0){
                        for(var key in response){
                            var val=response[key].id;
                            var name=response[key].name;
                            var vol=response[key].volume;
                            var opt=document.createElement('option');
                            opt.value=val;
                            opt.innerText=name+" 第"+vol+"期";
                            $("#course").append(opt);
                        }
                        $("#course").attr("disabled", false);
                    }
                }
            });
        }

        // 安排试听，以AJAX POST方式提交申请，返回ok或fail
        function experiencing() {
            var course_id = $("#course").val();
            var area_id = $("#area").val();
            if(course_id){
                $.post({
                    url:"/webapp/staff/exp_course/",
                    data:{"client_id": client_id, "course_id": course_id, "area_id": area_id},
                    dataType:"json",
                    success:function (response) {
                        if(response.status=='ok')
                            alert("已安排试听");
                        else
                            alert(response.msg);
                        window.location.reload();
                    }
                });
            }
        }
    </script>
</body>
</html>

day23/webapp/templates/app/followup-page.html
<div>
    <div>
        <button onclick="new_client()">添加客户</button>
    </div>
    <div class="follow_up_box">
        {% if ci %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>称谓</th>
                        <th>电话</th>
                        <th>QQ</th>
                        <th>Email</th>
                        <th>来源</th>
                        <th>工作人员</th>
                        <th>创建日期</th>
                    </tr>
                </thead>
                <tbody>
                    {% for client in ci %}
                    <tr onclick="show_follow_up_detail({{ client.id }});" class="">
                        <td>{{ client.name }}</td>
                        <td>{{ client.phone }}</td>
                        <td>{{ client.qq }}</td>
                        <td>{{ client.email }}</td>
                        <td>{{ client.get_source_display }}</td>
                        <td>{{ client.from_staff.cname }}</td>
                        <td>{{ client.create_at|date:"Y-m-d" }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            目前没有要跟进的客户
        {% endif %}
    </div>
    <script>
        function show_follow_up_detail(cid) {
            window.open("/webapp/staff/follow_up/detail/"+cid+"/");
        }
        function new_client() {
            window.open("/webapp/staff/follow_up/detail/new/");
        }
    </script>
</div>

day23/webapp/templates/app/login.bak.html
{% extends "base.html" %}
{% block title %}
登录
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
            {{ loginForm.as_table }}
        </table>
        <input type="submit" value="登录">
    </form>
{% endblock %}

day23/webapp/templates/app/manage-student-paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}" onclick="return open_page(this)"> &lt;&lt;</a>
        {% endif %}
        <span>
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}" onclick="return open_page(this)"> &gt;&gt;</a>
        {% endif %}
    </span>
    <script>
        function open_page(a) {
            var url = "/webapp/staff/manage_student/" + $(a).attr("href");
            $.get({
                url: url,
                dataType: "html",
                success: function (response) {
                    $("div.main").html(response);
                }
            });
            return false;
        }
    </script>
</div>

day23/webapp/templates/app/manage_student_list.html
<h1 class="page-header">学员信息</h1>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
              <th>姓名</th>
              <th>状态</th>
              <th>性别</th>
              <th>邮箱</th>
              <th>电话</th>
              <th>属区</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
              <td><a href="/webapp/staff/manage_student/{{ student.id }}/" target="_blank">{{ student.name }}</a></td>
              <td>{{ student.status }}</td>
              <td>{{ student.gender }}</td>
              <td>{{ student.email }}</td>
              <td>{{ student.phone }}</td>
              <td>{{ student.area.name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% include "app/manage-student-paginator.html" with page=students %}

day23/webapp/templates/app/new-clientinfo-success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>成功</title>
</head>
<body>
    <p>
        添加客户成功，您可以关闭该窗口，或者<a href=".">继续添加</a>
    </p>
</body>
</html>